### PR TITLE
cryptography and multiple curve support

### PR DESCRIPTION
**Pull request by whiteowl3**
Essentially a full line-by-line rewrite that removes PyOpenSSL entirely and transitions to cryptography with ~~SECP384R1~~ support for all reasonable curves.
Please pay careful attention to changes to tests.  Some sacrifices were made to move to cryptography, such as normalizing all ip strings, everwhere, to str(ipaddress.ip_address)
this changes our filenames, see tests.
~~the root_ca defaults to 10 years if it is not declared, although due to my laziness, and to keep the structure of the code from changing too much all at once, it's hacked a bit.  the caveat is that currently, if you explicitly create a root_ca with a not_valid_after value exactly equal to CERT_NOT_AFTER, it will create one with the hardcoded value instead without warning you.  There is a relevant comment describing this. It would be trivial to restore the original functionality if you preferred.~~

### CODE REVIEW

**Comment by whiteowl3** [comment]
actually my not_valid_after hack is just plain broken.

**Comment by ikreymer** [comment]
Thanks for this detailed rewrite! I assume motivation is just to remove the openssl dependency and update to more modern encryption libraries, right?
Perhaps the cert validity should be lower, I see there's #14 which lowered it already which didn't get a chance to merge yet..
It's been a while since updated this library, but want to make sure we get it right if for next update.

**Comment by whiteowl3** [comment]
requested changes are done plus a little extra sauce. 
default ca validity is three years
default host validity is 3 days
calling load_cert on a cached cert that is more than 1/3 expired will renew it
now means "now" instead of "when i initialized the ca"
pretty sure all functionality is g2g.  its a bit unintuitive that declaring cert_not_before/after in the constructor now applies to both the ca and the host certs, but you should not actually need to do this now. easy to fix later if it proves annoying.

**Comment by whiteowl3** [comment]
ack this has a print in it. hold up.

**Comment by whiteowl3** [comment]
constructor now takes ca_not_before/after and hosts_not_before/after
added tests for that and for cert renewal

**Comment by whiteowl3** [comment]
- [x] ~~examine and ensure correct KeyUsage (likely not optimal, possibly broken)~~
- [x] ~~examine "Issuer" field for host AND ca certs (likely broken)~~
- [ ] handle cryptography.exceptions.UnsupportedAlgorithm to failover if underlying openssl doesnt support defaults
- [ ] actually verify that these certs work
- [ ] clean up history
- [x] ~~update tests to account for multiple curves~~
- [ ] figure out example usage for requests
- [ ] see if there is a oneliner that will retrofit the openssl context functionality
- [ ] README.rst
- [ ] appveyor.yml
- [ ] travis.yml
- [ ] tox.ini
- [ ] setup.py

**Comment by whiteowl3** [comment]
@ikreymer  looks like 3.9, 3.10 are not available in your appveyor? Could you update to 2019 or 2022 at your convenience?

**Comment by whiteowl3** [comment]
back at my workstation, deleting this trash.

**Pull request closed without merging**
